# docker-compose.yml
version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8888
    volumes:
      - .:/app
    ports:
      - 8888:8888
    depends_on:
      - db 

  db:
    image: postgres:12.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

volumes:
  .:
  postgres_data:
  static: