# Generated by Django 3.1.3 on 2020-11-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20201111_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='id_tienda',
        ),
    ]
