# Generated by Django 3.1.3 on 2020-11-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
        ('catalogo', '0002_auto_20201112_1530'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('tienda', 'producto')},
        ),
    ]
