# Generated by Django 3.1.3 on 2020-11-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_remove_inventario_id_tienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
