# Generated by Django 3.1.3 on 2020-11-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
